# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-10 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', '静态图片'), ('2', '动态图片'), ('0', '全部')], max_length=2, verbose_name='图片类型')),
                ('start', models.IntegerField(verbose_name='起始图片id')),
                ('length', models.IntegerField(verbose_name='获取图片数量')),
                ('model', models.CharField(choices=[('1', '前取'), ('-1', '后取')], max_length=2, verbose_name='前/后取')),
                ('rank_id', models.IntegerField(verbose_name='缓存排行ID')),
                ('active_status', models.CharField(choices=[('1', '激活'), ('0', '去激活')], max_length=2)),
                ('address', models.CharField(max_length=500, verbose_name='链接地址')),
            ],
            options={
                'ordering': ['active_status'],
            },
        ),
    ]
