# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-10 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaperAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='length',
            field=models.IntegerField(blank=True, null=True, verbose_name='获取图片数量'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='model',
            field=models.CharField(blank=True, choices=[('1', '前取'), ('-1', '后取')], max_length=2, null=True, verbose_name='前/后取'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='缓存排行ID'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='start',
            field=models.IntegerField(blank=True, null=True, verbose_name='起始图片id'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='type',
            field=models.CharField(blank=True, choices=[('1', '静态图片'), ('2', '动态图片'), ('0', '全部')], max_length=2, null=True, verbose_name='图片类型'),
        ),
    ]
