# Generated by Django 2.1 on 2018-08-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaperAPI', '0002_auto_20180810_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, null=True, verbose_name='获取topic数量')),
                ('type', models.IntegerField(blank=True, choices=[('1', '只获取有壁纸的专题'), ('2', '只获取有link的专题'), ('3', '获取所有类型专题')], null=True, verbose_name='图片类型')),
                ('offset', models.IntegerField(blank=True, null=True, verbose_name='偏移量')),
                ('ordertype', models.IntegerField(blank=True, choices=[('1', '热度值倒序（desc）'), ('2', '热度值升序（asc）')], null=True, verbose_name='排序方式')),
                ('active_status', models.CharField(choices=[('1', '激活'), ('0', '去激活')], max_length=2)),
                ('address', models.CharField(max_length=500, verbose_name='链接地址')),
            ],
            options={
                'ordering': ['active_status'],
            },
        ),
    ]
