# Generated by Django 2.1 on 2018-08-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaperAPI', '0003_topiclist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiclist',
            name='ordertype',
            field=models.IntegerField(blank=True, choices=[(1, '热度值倒序（desc）'), (2, '热度值升序（asc）')], null=True, verbose_name='排序方式'),
        ),
        migrations.AlterField(
            model_name='topiclist',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '只获取有壁纸的专题'), (2, '只获取有link的专题'), (3, '获取所有类型专题')], null=True, verbose_name='图片类型'),
        ),
    ]
