# Generated by Django 2.1 on 2018-08-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallpaperAPI', '0005_guess_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(blank=True, choices=[(1, '是'), (0, '否')], null=True, verbose_name='获取全部')),
                ('hot', models.IntegerField(blank=True, choices=[(1, '是'), (0, '否')], null=True, verbose_name='获取热门')),
                ('length', models.IntegerField(blank=True, null=True, verbose_name='获取类别个数')),
                ('offset', models.IntegerField(blank=True, null=True, verbose_name='偏移量')),
                ('active_status', models.CharField(choices=[('1', '激活'), ('0', '去激活')], max_length=2)),
                ('address', models.CharField(max_length=500, verbose_name='链接地址')),
            ],
            options={
                'ordering': ['active_status'],
            },
        ),
    ]
